name: CI

on:
  push:
    branches: [ docs/*, ci/* ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint (flake8)
        run: |
          pip install flake8
          flake8 --max-line-length=120 || true

      - name: Run unit tests
        run: |
          pytest -q || exit 1

      - name: Fast smoke test ThreatMoE.run_single
        run: |
          python3 run_with_ckpt.py || exit 1
